@url = http://localhost:8080/api/v3

@token = eyJraWQiOiI0MjhiNDdmZi0zZTMwLTQ1NmUtOTkyYi1iYjgyMGNhMjVkNzAiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvaWRjLWNsaWVudCIsImF1ZCI6Im9pZGMtY2xpZW50IiwibmJmIjoxNzE2OTA3OTY3LCJzY29wZSI6WyJtZXNzYWdlLnJlYWQiLCJtZXNzYWdlLndyaXRlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcxNjkwODI2NywiaWF0IjoxNzE2OTA3OTY3LCJqdGkiOiI0ZTFkYmQ4ZS03NGM1LTQzZjAtOGM3Yi1lOWNkOWE5YTcyN2EifQ.rqzqRf-xbtTELj_xCRbWA7J_s0Ju5YuPAkILKUER02Zvbe_H3GPFcUqpFx9wXD18A_aZSaZPbjOGhjPhBLbF1JI_UNOI2V2guadKX0d2o29888gu5kM8S-scMoFEhVU2JA_wrdKUscIRt5PHX0OQ2vkajDHZZEAjx-gNpzI0tCKuwPbnLznjFOVxc4aUVtZinDs_C23bLx-spwSyomuHU5pPH2fMBBFbw7GpuFhpioX3oHvOLpisXEAIVrsBq2MbeIrTbPVUjAzlM_gPvLEU_hbYerfw9Mid0BuN-AHsfFS4-YWGivw6XH-X-QWqxAx5FUEFjpRHVJBsKw4ifG8DJw

GET {{url}}/beers
Authorization: Bearer {{token}}

###

GET {{url}}/beers?beerStyle=WHEAT

###

GET {{url}}/customers

###

GET http://localhost:8080/api/v3/beers
